# Generated by Django 2.2.5 on 2019-10-20 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userarticle',
            options={'ordering': ('headline',)},
        ),
        migrations.AlterModelOptions(
            name='userpublication',
            options={'ordering': ('title',)},
        ),
        migrations.AlterField(
            model_name='userarticle',
            name='employeetitles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserPublication'),
        ),
        migrations.AlterField(
            model_name='userarticle',
            name='publications',
            field=models.ManyToManyField(related_name='rritws', to='polls.UserPublication'),
        ),
    ]
