# Generated by Django 2.2.5 on 2019-10-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191020_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userarticle',
            old_name='publications',
            new_name='publicatins',
        ),
    ]
