# Generated by Django 2.2.5 on 2019-10-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20191020_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='userarticle',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='userpublication',
            options={'ordering': ('id',)},
        ),
    ]
