# Generated by Django 2.2.5 on 2019-10-25 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_exercise_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='level_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level_name_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='level_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level_name_id', models.CharField(max_length=100)),
                ('level_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.level_2')),
            ],
        ),
        migrations.CreateModel(
            name='level_4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('level_name_id', models.CharField(max_length=100)),
                ('level_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.level_3')),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.level_2')),
                ('level_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.level_3')),
                ('level_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.level_4')),
            ],
        ),
    ]
