# Generated by Django 2.2.5 on 2019-10-25 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_level_2_level_3_level_4_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='type',
            field=models.CharField( max_length=100),
            preserve_default=False,
        ),
    ]
