# Generated by Django 2.2.5 on 2019-10-25 05:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_position_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarti',
            name='position',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='jkk', to='polls.position'),
            preserve_default=False,
        ),
    ]
