# Generated by Django 2.2.5 on 2019-10-25 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_userarti_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarti',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jppkk', to='polls.position'),
        ),
    ]
