# Generated by Django 2.2.5 on 2019-10-25 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20191025_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='userarticle',
            name='position',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='polls.position'),
            preserve_default=False,
        ),
    ]
