# Generated by Django 2.2.5 on 2019-10-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_userarticle_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='type',
            new_name='types',
        ),
    ]
