# Generated by Django 2.2.5 on 2019-12-08 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20191204_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userarti',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Position'),
        ),
        migrations.AlterField(
            model_name='userarticle',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionss', to='polls.Position'),
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('odds', models.FloatField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='polls.Market')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startTime', models.DateTimeField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='polls.Market')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='polls.Sport')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ('startTime',),
            },
        ),
        migrations.AddField(
            model_name='market',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='polls.Sport'),
        ),
    ]
