# Generated by Django 2.2.5 on 2019-12-11 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20191210_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='userarti',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Position'),
        ),
        migrations.AlterField(
            model_name='userarticle',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionss', to='polls.Position'),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('toppings', models.ManyToManyField(to='polls.Topping')),
            ],
        ),
    ]
